simplenews_statistics.settings:
  type: config_object
  label: Settings
  mapping:
    simplenews_statistics_track_test:
      type: integer
    simplenews_statistics_track_mailto:
      type: integer
    simplenews_statistics_archive_days:
      type: integer
    simplenews_statistics_exclude:
      type: string
