simplenews_statistics.settings:
  type: config_object
  label: Settings
  mapping:
    track_test:
      type: integer
    track_mailto:
      type: integer
    archive_days:
      type: integer
    exclude:
      type: string
