<?php

/**
 * @file
 * Main simplenews statistics encoder file.
 */

/**
 * Implements hook_menu().
 */
function simplenews_statistics_encoder_menu() {
  $items['admin/config/services/simplenews/statistics/encoder'] = array(
    'title' => 'Parameter Encoding',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplenews_statistics_encoder_admin_settings_form'),
    'access arguments' => array('administer paramater encoding for newsletter statistics'),
    'file' => 'simplenews_statistics_encoder.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function simplenews_statistics_encoder_permission() {
  return array(
    'administer newsletter paramater encoding' => array(
      'title' => t('Administer newsletter paramater encoding'),
      'description' => t('Allows to administer parameter encoding settings for newsletter statistics.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_simplenews_statistics_decode_snid().
 */
function simplenews_statistics_encoder_simplenews_statistics_decode_snid($snid) {
  require_once drupal_get_path('module', 'simplenews_statistics_encoder') . '/encoder.inc';
  $decoded = simplenews_statistics_encoder_decode($snid);
  $salt = variable_get('simplenews_statistics_encoder_salt', 0);
  return $decoded - $salt;
}

/**
 * Implements hook_simplenews_statistics_decode_urlid().
 */
function simplenews_statistics_encoder_simplenews_statistics_decode_urlid($urlid) {
  require_once drupal_get_path('module', 'simplenews_statistics_encoder') . '/encoder.inc';
  $decoded = simplenews_statistics_encoder_decode($urlid);
  $salt = variable_get('simplenews_statistics_encoder_salt', 0);
  return $decoded - $salt;
}

/**
 * Implements hook_simplenews_statistics_encode_snid().
 */
function simplenews_statistics_encoder_simplenews_statistics_encode_snid($snid) {
  require_once drupal_get_path('module', 'simplenews_statistics_encoder') . '/encoder.inc';
  $salt = variable_get('simplenews_statistics_encoder_salt', 0);
  $salted = $snid + $salt;
  return simplenews_statistics_encoder_encode($salted);
}

/**
 * Implements hook_simplenews_statistics_encode_urlid().
 */
function simplenews_statistics_encoder_simplenews_statistics_encode_urlid($urlid) {
  require_once drupal_get_path('module', 'simplenews_statistics_encoder') . '/encoder.inc';
  $salt = variable_get('simplenews_statistics_encoder_salt', 0);
  $salted = $urlid + $salt;
  return simplenews_statistics_encoder_encode($salted);
}
